[version]
path = "src/descant/__about__.py"

[build.targets.sdist]
include = [
  "/src",
  "/tests",
]

[envs.default]
dependencies = [
  "pytest==7.1.3",
  "pytest-black==0.3.12",
  "pytest-cov==2.9.0",
  "pytest-flake8==1.1.1",
  "pytest-isort==3.0.0",
]

[envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=descant --cov=tests {args}"
no-cov = "cov --no-cov {args}"
serve = "python -m descant.web"

[[envs.test.matrix]]
python = ["37", "38", "39", "310", "311"]
