[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "descant"
description = 'A GDPR-compliant, JavaScript-based comment system.'
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
keywords = []
authors = [
  { name = "Keith Gaughan", email = "keith@gaughan.ie" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "click==8.0.3",
  "fastapi==0.81.0",
  "itsdangerous==2.1.2",
  "jinja2==3.0.1",
]
dynamic = ["version"]

[project.urls]
Documentation = "https://github.com/kgaughan/descant#readme"
Issues = "https://github.com/kgaughan/descant/issues"
Source = "https://github.com/kgaughan/descant"

[project.scripts]
descant = "descant.cli:descant"

[tool.hatch.build.targets.sdist]
include = [
  "/src",
  "/tests",
]

[tool.hatch.version]
path = "src/descant/__about__.py"

[tool.hatch.envs.default]
dependencies = [
  "pytest==7.1.3",
  "pytest-black==0.3.12",
  "pytest-cov==2.9.0",
  "pytest-flake8==1.1.1",
  "pytest-isort==3.0.0",
  "uvicorn[standard]==0.18.3",
]
[tool.hatch.envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=descant --cov=tests {args}"
no-cov = "cov --no-cov {args}"

[[tool.hatch.envs.test.matrix]]
python = ["37", "38", "39", "310", "311"]

[tool.coverage.run]
branch = true
parallel = true
omit = [
  "src/descant/__about__.py",
]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
